x-stoplight:
  docs:
    showModels: true
x-internal: true
openapi: 3.1.0
info:
  title: Articles Sync API Reference
  version: "1.0"
  contact:
    name: ''
    email: ''
  summary: Internal service for syncing articles between CloudMatrix and Playback Store
  tags:
  - name: Articles Sync
servers:
  - url: "https://cloudmatrix-articles-service.streamamg.com"
paths:
 '/articles/sync':
    post:
      summary: Articles Sync
      tags:
        - Articles Sync
      description: "Synchronizes articles from CM to Playback store
        In order to start sync process, the user must first be authenticated (via an API-Key). This token
        should be passed during the API call through the 'x-api-key' header"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                site:
                  type: string
                  description: 'Specifies the site whose articles are to be synchronized'             
                  default: 'cloudmatrix.dev.streamamg.com'
                  required:
                    - site          
      security:
        - x-api-key: []

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                description: Sync process for {site} initiated successfully
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
       
              examples:
                OK:
                  value:
                    message: Sync process for {site} initiated successfully   
                   
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                description: No api key provided
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message 
              examples:
                Unauthorized:
                  value:
                    message: API Key not provided or not valid  
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                description: Invalid request
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                BadRequest:
                  value:                    
                    message: Site should be provided  
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                description: Forbidden
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                BadRequest:
                  value:
                    message: Sync not enabled for {site}    
        404:
          description: Not Found
          content:
            application/json:
              schema:
                description: Not Found
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                BadRequest:
                  value:
                    message: Site {site} does not exist                                          
'/articles/sync2':
    post:
      summary: Articles Sync
      tags:
        - Articles Sync
      description: "Synchronizes articles from CM to Playback store
        In order to start sync process, the user must first be authenticated (via an API-Key). This token
        should be passed during the API call through the 'x-api-key' header"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                site:
                  type: string
                  description: 'Specifies the site whose articles are to be synchronized'             
                  default: 'cloudmatrix.dev.streamamg.com'
                  required:
                    - site          
      security:
        - x-api-key: []

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                description: Sync process for {site} initiated successfully
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
       
              examples:
                OK:
                  value:
                    message: Sync process for {site} initiated successfully   
                   
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                description: No api key provided
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message 
              examples:
                Unauthorized:
                  value:
                    message: API Key not provided or not valid  
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                description: Invalid request
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                BadRequest:
                  value:                    
                    message: Site should be provided  
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                description: Forbidden
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                BadRequest:
                  value:
                    message: Sync not enabled for {site}    
        404:
          description: Not Found
          content:
            application/json:
              schema:
                description: Not Found
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                BadRequest:
                  value:
                    message: Site {site} does not exist                                          
components:
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: ''
