x-stoplight:
  docs:
    showModels: true
x-internal: true
openapi: 3.1.0
info:
  title: Articles Internal Sync API Reference
  version: "1.0"
  contact:
    name: ''
    email: ''
  summary: Internal service for syncing articles between CloudMatrix and Playback Store
  tags:
  - name: Articles Internal Sync
servers:
  - url: "https://cloudmatrix-articles-service.streamamg.com"
paths:
 '/articles/sync2':
    post:
      summary: Articles Internal Sync
      tags:
        - Articles Internal Sync
      description: "Synchronizes articles from CM RDS to Playback DataStore
        In order to start sync process, the user must first be authenticated (via an API-Key). This token
        should be passed during the API call through the 'x-api-key' header"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                cmSite:
                  type: string
                  description: 'Specifies the CloudMatrix Site whose articles are to be synchronized'             
                  default: 'cloudmatrix.dev.streamamg.com'
                  required:
                    - cmSite          
      security:
        - x-api-key: []

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                description: Sync process for {site} initiated successfully
                type: object
                properties:
                  status:
                    type: number
                  success:
                    type: boolean
                  message:
                    type: string
                    minLength: 1
                  data: {
                    count: number
                  }
                required:
                  - message
                  - status
                  - message
                  - data
       
              examples:
                OK:
                  value:
                    status: 200
                    success: true
                    message: articles retrieved and sent to SQS successfully
                    data: {
                      count: 500
                    }  
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                description: Forbidden
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                BadRequest:
                  value:
                    message: API Key not provided or not valid   
        404:
          description: Not Found
          content:
            application/json:
              schema:
                description: Not Found
                type: object
                properties:
                  status:
                    type: number
                  success:
                    type: boolean
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
                  - status
                  - message       
              examples:
                BadRequest:
                  value:
                    message: "No connection details found for {CloudMatrix Instance}}"                                         
components:
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: ''
