openapi: 3.1.0
info:
  title: Image Service API
  version: 1.0.0
  license: 
    name: N/A
    url: https://notapplicable.com
  contact:
    name: Zeus Team
    email: zeusdevs@pamediagroup.com
    url: N/A
  summary: An API to retrieve multiple formats of image assets. // TODO improve
  description: |-
    // TODO improve
tags:
  - name: Images
    description: Images tag
servers:
  - url: 'https://images.streamamg.com'
paths:
  /images/{id}/renditions:
    get:
      operationId: get-image-renditions
      summary: Fetch all available renditions of an image
      description: // TODO
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Unique ID of the image
      responses:
        '200':
          description: //TODO
          content:
            application/json:
              schema:
                type: object
                properties:
                  renditions:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        width:
                          type: integer
                        url:
                          type: string
                          format: uri
                examples:
                  value:
                    renditions:
                      '320w.jpg':
                        width: 320
                        url: https://yourwebsite.com/images/image-src-320w.jpg
                      '480w.jpg':
                        width: 480
                        url: https://yourwebsite.com/images/image-src-480w.jpg
        '404':
          description: Image not found 
        '500':
          description: Server error
  /images/{id}:
    get:
      operationId: get-by-id
      summary: Fetch image details and the image
      description: Fetch image details and the image // TODO
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Unique ID of the image
      - name: width
        in: query
        schema:
          type: integer
          minimum: 1
        description: Desired width of the image
      - name: height
        in: query
        schema:
          type: integer
          minimum: 1
        description: Desired height of the image
      responses:
        '200':
          description: Image details and url
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  width:
                    type: integer
                  height:
                    type: integer
                  format:
                    type: string
                  url:
                    type: string

        '404':
          description: Image not found
        '500':
          description: Server error