x-internal: true
x-stoplight:
  id: tqnb0nc0s88d2
openapi: 3.1.0
info:
  title: SNS Subscription API Reference
  version: '1.0'
  contact:
    name: ''
    email: ''
  summary: Internal SNS Subscription Service API for CloudMatrix.
  description: |-
    The SNS Subscription Service API exposes the functionality to create, read and delete CloudMatrix SNS Subscription 
    Webhooks and is for internal use only (typically the CloudMatrix UI will utilise these endpoints to allow users to manage their subscriptions).
servers:
  - url: 'https://cloudmatrix-events-api.dev.streamamg.com/api/v1/'
paths:
  '/subscription/{id}':
    delete:
      summary: Delete a single SNS Subscription from CloudMatrix
      description: |-
        This endpoint deletes an existing subscription based on its unique id. The client must provide a valid tenant-id in the request headers to identify the tenant context under which the subscription operates.
        If successful, the server responds with a 204 No Content status, indicating that the subscription was deleted without returning any content in the response body.

        Note that this is a full removal of the entry, not a soft removal.

        The user must first be authenticated (via an API-Key). This token should be passed during the API call through the 'x-api-key' header. 
      tags:
        - SNS-Subscription
      operationId: delete-sns-subscription-data
      security:
        - ApiKey: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: SNS Subscription in CloudMatrix to be deleted
        - in: header
          name: tenant-id
          description: The unique identifier of the tenant
          required: true
          schema:
            type: string
            format: uuid
        - in: header
          name: x-api-key
          description: The x-api-key
          required: true
          schema:
            type: string
            format: string
      responses:
        '204':
          description: SNS Subscription is deleted in CloudMatrix
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: Invalid/Missing API Key
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Invalid API Key:
                  value:
                    message: API Key not provided or not valid
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                description: "Subscription: {id} not found"
                type: object
                properties:
                  status:
                    type: number
                    enum:
                      - 404
                  message:
                    type: string
                    minLength: 1
                  reason:
                    type: string
                    minLength: 1
                required:
                  - statusCode
                  - message
                  - error
              examples:
                Invalid Event Id:
                  value:
                    message: "Subscription: 354a82b8-fb50-45fe-8b78-c952b06e2a82 not found"
                    error: Not Found
                    statusCode: 404
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: Error deleting SNS Subscription data
                type: object
                properties:
                  statusCode:
                    type: number
                    enum:
                      - 500
                  message:
                    type: string
                    minLength: 1
                required:
                  - status
                  - message
                  - error
              examples:
                Internal Server Error:
                  value:
                    message: 'Subscription deletion failed'
                    error: Internal Server Error
                    statusCode: 500
      x-stoplight:
        id: zfms911lbsgx2
    parameters:
      - schema:
          type: string
        in: header
        name: tenant-id
        description: UUID identifying tenant
        required: true
  /event:
    post:
      summary: Create a new event in CloudMatrix
      description: |
        Create a new event in CloudMatrix for a tenant identified by the header parameter 'tenant-id'.

        In order to create the event data, the user must first be authenticated (via an API-Key). This token
        should be passed during the API call through the 'x-api-key' header.
      tags:
        - SNS-Subscription
      security:
        - ApiKey: []
      operationId: create-event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventBody'
            examples:
              Event with singular attributes:
                value:
                  typeId: b5c3a174-1b00-4495-a4cb-f030d475b4b9
                  priorityOrder: 1
                  title: 'Football Match: Barcelona vs Real Madrid'
                  subtitle: El Clasico
                  description: This is a highly anticipated football match between two of the biggest clubs in the world.
                  start: '2023-05-21T19:00:00Z'
                  end: '2023-05-21T21:00:00Z'
                  offset: 0
                  entries:
                    - id: 4a5b0d0c-2f1b-4e9f-b0f0-6a97e91a1236
                    - id: e078d72a-aad4-4b68-9227-e0bde0b35c66
                  attributes:
                    - id: 4a5b0d0c-2f1b-4e9f-b0f0-6a97e91a1234
                      value: custom string attribute
                    - id: 7b8c2e5a-1a2b-4c3d-e4f5-6789abcdef01
                      value: '42'
              Event with mixed attributes:
                value:
                  value:
                    typeId: b5c3a174-1b00-4495-a4cb-f030d475b4b9
                    priorityOrder: 1
                    title: 'Football Match: Barcelona vs Real Madrid'
                    subtitle: El Clasico
                    description: This is a highly anticipated football match between two of the biggest clubs in the world.
                    start: '2023-05-21T19:00:00Z'
                    end: '2023-05-21T21:00:00Z'
                    offset: 0
                    entries:
                      - id: 4a5b0d0c-2f1b-4e9f-b0f0-6a97e91a1236
                      - id: e078d72a-aad4-4b68-9227-e0bde0b35c66
                    attributes:
                      - id: 4a5b0d0c-2f1b-4e9f-b0f0-6a97e91a1234
                        value: custom string attribute
                      - id: e078d72a-aad4-4b68-9227-e0bde0b35c6z
                        items:
                          - value: dropdownValue1
                          - value: dropdownValue2
      responses:
        '201':
          description: Created new event in CloudMatrix
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventData'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: Invalid request data for the event to create
                type: object
                properties:
                  statusCode:
                    type: number
                    enum:
                      - 400
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    enum:
                      - Bad Request
                required:
                  - statusCode
                  - message
                  - error
              examples:
                Invalid Event Identifier:
                  value:
                    status: 400
                    message: id must be a UUID
                    error: Bad Request
                Title Is Required:
                  value:
                    status: 400
                    message: Title must be a non-empty object
                    error: Bad Request
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: Invalid/Missing API Key
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Invalid API Key:
                  value:
                    message: Forbidden
        '500':
          description: Internal Server Error
      x-stoplight:
        id: p7xw6sda7vuh1
    parameters:
      - schema:
          type: string
        in: header
        name: tenant-id
        description: UUID identifying tenant
        required: true
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    EventData:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Event id
        typeId:
          type: string
          format: uuid
          description: Custom event type id
        priorityOrder:
          type: integer
          minimum: 0
          description: Event priority order used when displaying events
        title:
          type: string
          minLength: 1
          description: Event's main title
        subtitle:
          type: string
          minLength: 0
          description: Event's secondary title
        description:
          type: string
          minLength: 0
          description: Event's description
        start:
          type: string
          format: date-time
          description: Start time of the event
        end:
          type: string
          format: date-time
          description: End time of the event
        offset:
          type: number
          minimum: 0
          description: Extra minutes before start time when event can be advertised
        attributes:
          $ref: '#/components/schemas/EventAttributes'
        entries:
          $ref: '#/components/schemas/MediaEntries'
        createdAt:
          type: string
          x-stoplight:
            id: sagujd3k325dy
          format: date-time
        updatedAt:
          type: string
          x-stoplight:
            id: 7iybtu6zsekc6
          format: date-time
      x-stoplight:
        id: ewk4f9lm2hqcb
    EventDataList:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/EventData'
        pagination:
          $ref: '#/components/schemas/Pagination'
      x-stoplight:
        id: tf1o74n02fdrh
    CreateEventBody:
      type: object
      x-stoplight:
        id: gey87qt7ekx7o
      title: CreateEventBody
      required:
        - typeId
        - title
        - priorityOrder
        - start
        - end
      properties:
        typeId:
          type: string
          format: uuid
          description: Custom event type id
        title:
          type: string
          minLength: 1
          description: Event's main title
        description:
          type: string
          minLength: 0
          description: Event's description
        priorityOrder:
          type: integer
          minimum: 0
          description: Event priority order used when displaying events
        subtitle:
          type: string
          minLength: 0
          description: Event's secondary title
        start:
          type: string
          format: date-time
          description: Start time of the event
        end:
          type: string
          format: date-time
          description: End time of the event
        offset:
          type: number
          minimum: 0
          description: Extra minutes before start time when event can be advertised
        attributes:
          $ref: '#/components/schemas/EventAttributes'
        entries:
          $ref: '#/components/schemas/MediaEntries'
    EventAttributes:
      type: array
      x-stoplight:
        id: dfqlt93r36p2k
      uniqueItems: true
      minItems: 1
      description: The metadata attributes
      items:
        type: object
        required:
          - id
        properties:
          id:
            type: string
            minLength: 1
            description: CloudMatrix attribute configuration id
            format: uuid
          value:
            type: string
            minLength: 1
            description: 'CloudMatrix attribute value (singular value like string, number etc.)'
          valueId:
            type: string
            description: CloudMatrix attribute config option id (if for example attribute config represents a dropdown with predefined values)
          items:
            type: array
            uniqueItems: true
            minItems: 1
            description: CloudMatrix attribute value (collection)
            items:
              type: object
              additionalProperties: false
              required:
                - value
              properties:
                value:
                  type: string
                  minLength: 1
                  description: 'CloudMatrix attribute value (singular value like string, number etc.)'
                valueId:
                  type: string
                  description: CloudMatrix attribute config option id (if for example attribute config represents a multichoice checkbox with predefined values)
    MediaEntries:
      type: array
      x-stoplight:
        id: desads8z02311
      uniqueItems: true
      minItems: 1
      description: The wideo and audio entries details (itemData)
      title: ItemData
      items:
        type: object
        required:
          - id
        properties:
          id:
            type: string
            minLength: 1
            description: CloudMatrix article id
            format: uuid
    Pagination:
      type: object
      x-stoplight:
        id: 74bgl7ah1xkhz
      properties:
        totalCount:
          type: integer
          x-stoplight:
            id: 9n82xqtwy974s
        itemCount:
          type: integer
        pageSize:
          type: integer
        pageIndex:
          type: integer
tags:
  - name: SNS-Subscription
