openapi: 3.1.0
info:
  title: Upload API
  version: '1.0'
  summary: An API to facilitate the uploading of media Content into StreamAMGs CloudMatrix & MediaPlatform Products
  description: |-
    The CloudMatrix Upload API provides clients with the functionality to upload Media Content via a HTTP API with no dependencies on a technology or framework.

    The upload functionality allows clients to upload Rich Metadata alongside their media so that it is automatically available within CloudMatrix once the media entry is processed via MediaPlatform. 
servers: []
paths:
  /upload:
    parameters: []
    put:
      summary: Upload
      operationId: put-upload
      responses:
        '200':
          description: OK
      description: |-
        In order to upload a media entry, first a initial API call to retrive a signed URL must be generated. This signed URL will allow you to directly upload the media asset to the storage location via HTTP.

        The initial API call should consist of metadata you would like to store against your asset within the CloudMatrix Platform and any associated entitlements for the entry you are uploading.

        Note: This method of upload only supports upto 5GB per asset, for larger assets please refer to the multipart upload.
      tags:
        - Upload
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                id:
                  type: string
                  minLength: 1
                title:
                  type: string
                  minLength: 1
                description:
                  type: string
                  minLength: 1
                metadata:
                  type: object
                  properties:
                    originalReleaseDate:
                      type: string
                      minLength: 1
                  required:
                    - originalReleaseDate
                entitlements:
                  type: array
                  items:
                    required: []
                    properties: {}
              required:
                - id
                - title
                - description
                - metadata
                - entitlements
              x-examples:
                example-1:
                  id: 27b24738-7f6b-11ec-a8a3-0242ac120002
                  title: Example 1
                  description: A brief description of the example 1 video
                  metadata:
                    originalReleaseDate: '2022-01-01'
                  entitlements:
                    - monthly99
                    - premium
            examples:
              Example:
                value:
                  id: 27b24738-7f6b-11ec-a8a3-0242ac120002
                  title: Example 1
                  description: A brief description of the example 1 video
                  metadata:
                    originalReleaseDate: '2022-01-01'
                  entitlements:
                    - monthly99
                    - premium
        description: The body should contain the additional CloudMatrix Metadata you would like to store along side the entry.
  /multipart/start:
    put:
      summary: Start Multipart Upload
      operationId: put-multipart-start
      responses:
        '200':
          description: OK
      description: ''
      tags:
        - Multipart
  /multipart/complete:
    put:
      summary: Start Multipart Upload
      operationId: put-multipart-start
      responses:
        '200':
          description: OK
      description: ''
      tags:
        - Multipart
    parameters: []
components:
  schemas: {}
